# Generated by Django 2.1.4 on 2019-05-09 07:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ent',
            fields=[
                ('entid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('question', models.CharField(max_length=20)),
                ('answer', models.CharField(max_length=20)),
                ('tel', models.CharField(max_length=15)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ent_baseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entLocation', models.CharField(max_length=20)),
                ('entName', models.CharField(max_length=20)),
                ('entEmail', models.CharField(max_length=20)),
                ('entIntroduction', models.TextField()),
                ('entid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ent')),
            ],
        ),
        migrations.CreateModel(
            name='ent_jobs',
            fields=[
                ('jobid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('enterpriseName', models.CharField(max_length=50)),
                ('jobsName', models.CharField(max_length=20)),
                ('jobsCodition', models.CharField(max_length=30)),
                ('jobsLocation', models.CharField(max_length=30)),
                ('jobsPay', models.CharField(max_length=30)),
                ('entid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ent')),
            ],
        ),
        migrations.CreateModel(
            name='psn',
            fields=[
                ('psnid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('question', models.CharField(max_length=20)),
                ('answer', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
                ('tel', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='psn_resume',
            fields=[
                ('resumeid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=20)),
                ('nowJobs', models.CharField(max_length=20)),
                ('nowPay', models.CharField(max_length=20)),
                ('personIntroduction', models.TextField()),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('industry', models.CharField(max_length=20)),
                ('function', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('companyName', models.CharField(max_length=20)),
                ('startWork', models.CharField(max_length=20)),
                ('psnid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.psn')),
            ],
        ),
    ]
