# Generated by Django 2.1.4 on 2019-02-08 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='enterprise',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('question', models.CharField(max_length=20)),
                ('answer', models.CharField(max_length=20)),
                ('enterpriseemail', models.CharField(max_length=20)),
                ('enterpriseName', models.CharField(max_length=50)),
                ('enterpriseNumber', models.CharField(max_length=50)),
                ('enterpriseIntroduction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='enterprise_jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enterpriseName', models.CharField(max_length=50)),
                ('jobsName', models.CharField(max_length=20)),
                ('jobsCodition', models.CharField(max_length=30)),
                ('jobsLocation', models.CharField(max_length=30)),
                ('jobsPay', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('question', models.CharField(max_length=20)),
                ('answer', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='person_baseInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('industry', models.CharField(max_length=20)),
                ('function', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('companyName', models.CharField(max_length=20)),
                ('startWork', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='person_resume',
            fields=[
                ('relName', models.AutoField(primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('nowJobs', models.CharField(max_length=20)),
                ('nowPay', models.CharField(max_length=20)),
                ('personIntroduction', models.TextField()),
            ],
        ),
    ]
