# Generated by Django 2.1.4 on 2019-05-22 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='psn_resume',
            name='degree',
            field=models.CharField(default='本科', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ent_baseinfo',
            name='entTag',
            field=models.TextField(default='五险一金'),
        ),
    ]
