# Generated by Django 2.1.4 on 2018-12-30 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='polls_model',
            old_name='context',
            new_name='content',
        ),
    ]
