# Generated by Django 2.1.4 on 2018-12-27 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='polls_model',
            name='context',
            field=models.TextField(),
        ),
    ]
