# Generated by Django 2.1.4 on 2019-05-09 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190506_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='ent',
            fields=[
                ('entid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('question', models.CharField(max_length=20)),
                ('answer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ent_baseInfo',
            fields=[
                ('entid', models.AutoField(max_length=64, primary_key=True, serialize=False)),
                ('entLocation', models.CharField(max_length=20)),
                ('entName', models.CharField(max_length=20)),
                ('entEmail', models.CharField(max_length=20)),
                ('entIntroduction', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ent_jobs',
            fields=[
                ('jobid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('enterpriseName', models.CharField(max_length=50)),
                ('jobsName', models.CharField(max_length=20)),
                ('jobsCodition', models.CharField(max_length=30)),
                ('jobsLocation', models.CharField(max_length=30)),
                ('jobsPay', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='psn',
            fields=[
                ('psnid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=20)),
                ('password', models.CharField(max_length=20)),
                ('question', models.CharField(max_length=20)),
                ('answer', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='psn_resume',
            fields=[
                ('resumeid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('gender', models.CharField(max_length=20)),
                ('nowJobs', models.CharField(max_length=20)),
                ('nowPay', models.CharField(max_length=20)),
                ('personIntroduction', models.TextField()),
                ('name', models.CharField(max_length=20)),
                ('sex', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=20)),
                ('industry', models.CharField(max_length=20)),
                ('function', models.CharField(max_length=20)),
                ('position', models.CharField(max_length=20)),
                ('companyName', models.CharField(max_length=20)),
                ('startWork', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='enterprise',
        ),
        migrations.DeleteModel(
            name='enterprise_jobs',
        ),
        migrations.DeleteModel(
            name='person',
        ),
        migrations.DeleteModel(
            name='person_baseInfo',
        ),
        migrations.DeleteModel(
            name='person_resume',
        ),
    ]
