# Generated by Django 2.1.4 on 2019-05-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20190522_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='send_job',
            name='entemail',
            field=models.CharField(default='987073656@qq.com', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='send_job',
            name='enttel',
            field=models.CharField(default='13756053551', max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='send_job',
            name='psnemail',
            field=models.CharField(default='987073656@qq.com', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='send_job',
            name='psntel',
            field=models.CharField(default='13756053551', max_length=15),
            preserve_default=False,
        ),
    ]
