# Generated by Django 2.1.4 on 2019-05-11 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_auto_20190511_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='ent_baseinfo',
            name='entClass',
            field=models.CharField(default='私营企业', max_length=20),
        ),
        migrations.AddField(
            model_name='ent_baseinfo',
            name='entScale',
            field=models.CharField(default='1-49人', max_length=20),
        ),
        migrations.AlterField(
            model_name='ent_baseinfo',
            name='entContectName',
            field=models.CharField(default='HR', max_length=20),
        ),
    ]
