# Generated by Django 2.1.4 on 2019-05-14 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_auto_20190513_1659'),
    ]

    operations = [
        migrations.RenameField(
            model_name='psn_resume',
            old_name='companyName',
            new_name='jobAdd',
        ),
        migrations.RenameField(
            model_name='psn_resume',
            old_name='function',
            new_name='jobName',
        ),
        migrations.RenameField(
            model_name='psn_resume',
            old_name='gender',
            new_name='jobPay',
        ),
        migrations.RenameField(
            model_name='psn_resume',
            old_name='industry',
            new_name='jobType',
        ),
        migrations.RemoveField(
            model_name='psn_resume',
            name='nowJobs',
        ),
        migrations.RemoveField(
            model_name='psn_resume',
            name='nowPay',
        ),
        migrations.RemoveField(
            model_name='psn_resume',
            name='personIntroduction',
        ),
        migrations.RemoveField(
            model_name='psn_resume',
            name='position',
        ),
        migrations.RemoveField(
            model_name='psn_resume',
            name='startWork',
        ),
        migrations.AddField(
            model_name='psn_resume',
            name='age',
            field=models.IntegerField(default=0),
        ),
    ]
