# Generated by Django 2.1.4 on 2019-05-14 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0009_auto_20190514_1534'),
    ]

    operations = [
        migrations.AddField(
            model_name='psn_resume',
            name='nowStatus',
            field=models.CharField(default='0', max_length=2),
        ),
    ]
