# Generated by Django 2.1.4 on 2019-05-14 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_psn_resume_nowstatus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psn_resume',
            name='jobName',
            field=models.CharField(max_length=30),
        ),
    ]
