# Generated by Django 2.1.4 on 2019-05-14 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_auto_20190514_1648'),
    ]

    operations = [
        migrations.CreateModel(
            name='psn_resume_edu_exprience',
            fields=[
                ('eduid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('majorName', models.CharField(max_length=30)),
                ('schoolName', models.CharField(max_length=50)),
                ('gradTime', models.DateField()),
                ('degree', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='psn_resume_project_exprience',
            fields=[
                ('projectid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('jobName', models.CharField(max_length=30)),
                ('orgName', models.CharField(max_length=50)),
                ('startTime', models.DateField()),
                ('endTime', models.DateField()),
                ('tecName', models.CharField(max_length=30)),
                ('projectDisp', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='psn_resume_work_exprience',
            fields=[
                ('workid', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('jobName', models.CharField(max_length=30)),
                ('companyName', models.CharField(max_length=50)),
                ('startTime', models.DateField()),
                ('endTime', models.DateField()),
                ('workDisp', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='psn_resume',
            name='updateTime',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='psn_resume_work_exprience',
            name='resumeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.psn_resume'),
        ),
        migrations.AddField(
            model_name='psn_resume_project_exprience',
            name='resumeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.psn_resume'),
        ),
        migrations.AddField(
            model_name='psn_resume_edu_exprience',
            name='resumeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.psn_resume'),
        ),
    ]
