# Generated by Django 2.1.4 on 2019-05-15 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_auto_20190514_1757'),
    ]

    operations = [
        migrations.CreateModel(
            name='send_job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sendTime', models.DateField(auto_now=True)),
                ('jobid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.ent_jobs')),
            ],
        ),
        migrations.AlterField(
            model_name='psn_resume',
            name='updateTime',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='send_job',
            name='resumeid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.psn_resume'),
        ),
    ]
