# Generated by Django 2.1.4 on 2019-05-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_auto_20190515_1208'),
    ]

    operations = [
        migrations.AddField(
            model_name='psn_resume_project_exprience',
            name='projectName',
            field=models.CharField(default='项目名称', max_length=30),
        ),
    ]
