# Generated by Django 2.1.4 on 2019-05-15 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_psn_resume_project_exprience_projectname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psn_resume_project_exprience',
            name='projectName',
            field=models.CharField(max_length=30),
        ),
    ]
