# Generated by Django 2.1.4 on 2019-05-16 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_auto_20190515_1448'),
    ]

    operations = [
        migrations.AlterField(
            model_name='psn_resume_edu_exprience',
            name='gradTime',
            field=models.IntegerField(default=2019),
        ),
    ]
