# Generated by Django 2.1.4 on 2019-05-16 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0016_auto_20190516_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='psn_resume',
            name='selfDisp',
            field=models.TextField(default='请输入一段自我描述'),
        ),
    ]
