# Generated by Django 2.1.4 on 2019-05-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0019_auto_20190517_1259'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ent_jobs',
            old_name='jobsCodition',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='ent_jobs',
            old_name='enterpriseName',
            new_name='jobClass',
        ),
        migrations.RenameField(
            model_name='ent_jobs',
            old_name='jobsLocation',
            new_name='jobDepart',
        ),
        migrations.RenameField(
            model_name='ent_jobs',
            old_name='jobsPay',
            new_name='jobLocation',
        ),
        migrations.RenameField(
            model_name='ent_jobs',
            old_name='jobsName',
            new_name='jobName',
        ),
        migrations.AddField(
            model_name='ent_jobs',
            name='degree',
            field=models.CharField(default='大专', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ent_jobs',
            name='jobAddress',
            field=models.CharField(default='详细地址', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ent_jobs',
            name='jobPay',
            field=models.CharField(default='5-8W', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ent_jobs',
            name='jobReq',
            field=models.TextField(default='任职要求'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ent_jobs',
            name='jobType',
            field=models.CharField(default='全职', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ent_jobs',
            name='workExp',
            field=models.CharField(default='应届毕业生', max_length=15),
        ),
    ]
