# Generated by Django 2.1.4 on 2019-05-17 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0020_auto_20190517_1414'),
    ]

    operations = [
        migrations.AddField(
            model_name='ent_jobs',
            name='updateTime',
            field=models.DateField(auto_now=True),
        ),
    ]
