# Generated by Django 2.1.4 on 2019-05-18 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0021_ent_jobs_updatetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='ent_baseinfo',
            name='entTag',
            field=models.TextField(default='五险一金'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ent_jobs',
            name='workExp',
            field=models.CharField(default='不限', max_length=15),
        ),
    ]
