# Generated by Django 2.1.4 on 2019-05-19 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0022_auto_20190518_1302'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ent_jobs',
            name='jobLocation',
        ),
    ]
